### ISSUE TITLE
originally logged out but still profile and logout options are displayed  at the same screen 

### ISSUE THREAD

**Issue by faizalredfort** [megamsys/megam.io#19]
@megamsys/core @megamsys/megam-dev 
![screenshot from 2016-10-13 22-32-29](https://cloud.githubusercontent.com/assets/16361574/19379705/fb599648-9210-11e6-807e-7aca852af0be.png)

**Comment by indykish** [comment]
@vinomca-megam Please educate @faizalredfort  on creating issues for nilavu and move this issue over to gitlab.

Hopefully he has access to https://gitlab.com/megamsys/nilavu.
